// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "3d9ea5deaff720960af6db37413cf5ffd43d8345a1febeaeaa02805e82687df0")
